---
apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: demo-deployment 
spec: 
  replicas: 3 
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
      - name: nginx 
        image: nginx:1.7.9 
        ports: 
        - containerPort: 80
      - name: mysql-test-c
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
    nodePort: 30006
  selector:
    app: nginx

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-traefik-ingress
spec:
  rules:
  - host: nginx.k8s.medusec.com
    http:
      paths:
      - path: /
        backend:
          serviceName: demo-nginx-service
          servicePort: 80