---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: web
spec:
  containers:
  - name: nginx-test-c
    image: nginx
    ports:
    - containerPort: 80
  - name: mysql-test-c
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123456"
    ports:
    - containerPort: 3306
  
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-1
  labels:
    app: web-1
spec:
  containers:
  - name: nginx-test-c
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-test
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
    nodePort: 30006
  selector:
    app: web
